name: Build and Test
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
      - name: Setup Yarn
        uses: ./.github/actions/setup-yarn
      - name: Install
        run: yarn install --no-immutable
      - name: Build
        run: yarn build
      - name: Type
        run: yarn dtsc
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
